name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # NOTE: UTCなので9時間引く
    # 毎週土曜日の22時に実行
    - cron: 0 11 * * 6
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.20.0
          cache: yarn

      - name: Install node packages
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run type check
        run: yarn type-check

      - name: Run test
        run: yarn test
